MIN_GENRE_SAMPLES_COUNT = 100

FRAME_LENGTH_MS = 25
HOP_LENGTH_MS = 10

NUMBER_OF_MFCC_TO_RETURN = 8
MEL_BANDS_NUMBER = 26
NUMBER_OF_RETAINED_COEFFICIENTS = 8
DELTA_WINDOW_WIDTH = 5

VAL_RATIO = 0.15
TEST_RATIO = 0.15
